### ISSUE TITLE
Allow to provide reports directory on the command line

### ISSUE THREAD

**Issue by nwinkler** [bogus-weber/xunit-reports-viewer#2]
It would be great to be able to specify the `reports` directory name on command line. Currently, the value is hard coded to `reports`, and `xunit-viewer` fails if there is no directory called `reports`.

Can you consider adding a parameter that allows to specify the directory of the test files? If the parameter is not provided, it should default to `reports`.

**Comment by bogus-weber** [comment]
you can now use command arguments to set custom reports dir, for example: ```xunit-viewer -r ../anotherReportsDir```
Also there is a small help message available with -h argument

**Comment by nwinkler** [comment]
Thanks - works great!
